#!/bin/bash
# ⚡ SCHNELLE CRON-SETUP ANLEITUNG

echo "🤖 SPD Scraper - Cron Setup"
echo "================================"
echo ""
echo "Schritt 1: Öffne Crontab Editor"
echo "  → Terminal eingeben:"
echo ""
echo "    crontab -e"
echo ""
echo "Schritt 2: Füge diese Zeile ein (Täglich um 9:00 Uhr):"
echo ""
echo "    0 9 * * * /Users/alperredzepov/scraper/run_scraper.sh >> /Users/alperredzepov/scraper/logs/scraper.log 2>&1"
echo ""
echo "Schritt 3: Speichern & Beenden"
echo "  → Drücke: Ctrl+X"
echo "  → Drücke: Y"
echo "  → Drücke: Enter"
echo ""
echo "Schritt 4: Überprüfe dass es eingetragen ist"
echo "  → Terminal eingeben:"
echo ""
echo "    crontab -l"
echo ""
echo "Schritt 5: Logs ansehen (optional)"
echo "  → Terminal eingeben:"
echo ""
echo "    tail -f /Users/alperredzepov/scraper/logs/scraper.log"
echo ""
echo "================================"
echo "✅ Setup fertig! Der Scraper läuft jetzt täglich um 9:00 Uhr"
echo ""
